### ISSUE TITLE
Returns an Exception when all the values get zero in data

### ISSUE THREAD

**Issue by TharinduKetipe** [fgcan10/chart_components#6]
Hi!
I'm showing a graph by getting some booking data through an API. Sometimes booking count will be zero for all the days of the week.. When I pass booking count array of zeros (0.0) as the data of BarChart it will returns the following exception.
`'package:flutter/src/widgets/basic.dart': Failed assertion: line 2310 pos 15: 'heightFactor == null || heightFactor >= 0.0': is not true.`

How could I draw the chart in these kind of situations?
Thank you!

**Comment by fgcan10** [comment]
Hi,

Thanks for reporting this issue!
 I'll have a look and make a new version to solve this problem!

**Comment by fgcan10** [comment]
Hi,

Problem is solved. 
Please upgrade to version 0.1.6

Regards,
